import './App.css';
import { useState } from 'react';
import React from 'react';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
import TeacherBio from './Components/TeacherBio';
import Filter from './Components/Filter'; 
import StudentForm from './Components/Student';
import Teacherfrom from './Components/Teacher';
import StudentFilter from './Components/StudentFilter';

function App() {
  const questions = [
    "1. Knowledge base of the teacher (as perceived by you)",
    "2. Communication skills (in terms of articulation and comprehensibility)",
    "3. Sincerity / Commitment of the teacher (in terms of preparedness and interest in taking classes)",
    "4. Interest generated by the teacher in the class",
    "5. Ability to integrate course material with environment / other issues, to provide a broader perspective",
    "6. Accessibility and availability of the teacher in the department for academic consultations",
    "7. Initiative taken in formulating topics/ tests/assignments/examinations / seminars and projects",
    "8. Regularity in taking classes",
    "9. Completion of the course in a thorough and satisfactory manner",
    "10. Fairness in evaluating student performance and awarding grades.",
    "11. Overall rating of Your Teachers"
  ];

  const [ratings, setRatings] = useState(Array(11).fill(0)); 
  const [hovers, setHovers] = useState(Array(11).fill(0)); 
  const [suggestion, setSuggestion] = useState(''); 

  const handleRatingClick = (index, num) => {
    const newRatings = [...ratings];
    newRatings[index] = num;
    setRatings(newRatings);
  };

  const handleHover = (index, num) => {
    const newHovers = [...hovers];
    newHovers[index] = num;
    setHovers(newHovers);
  };

  const handleMouseLeave = (index) => {
    const newHovers = [...hovers];
    newHovers[index] = ratings[index];
    setHovers(newHovers);
  };

  const handleSuggestionChange = (event) => {
    setSuggestion(event.target.value);
  };

  const renderStarRating = (index) => {
    return (
      <div>
        {[1, 2, 3, 4, 5].map((num) => (
          <button
            key={num}
            onClick={() => handleRatingClick(index, num)}
            onMouseOver={() => handleHover(index, num)}
            onMouseLeave={() => handleMouseLeave(index)}
          >
            <span className={`star ${num <= (hovers[index] || ratings[index]) ? 'on' : 'off'}`}>
              &#9733;
            </span>
          </button>
        ))}
      </div>
    );
  };

  return (
    <Router>
      <div className="App">
        <Routes>
          {/* Main filter and rating page */}
          <Route 
            path="/" 
            element={
              <>
                <h1>Rate Your Advice Towards your Teacher</h1>

                {questions.map((question, index) => (
                  <div key={index}>
                    <h2 className="question">{question}</h2>
                    {renderStarRating(index)}
                  </div>
                ))}

                {/* Suggestion input box at the end */}
                <div className='suggestion-box'>
                  <h2>ADD YOUR SUGGESTION</h2>
                  <textarea
                    placeholder="Write your suggestion here"
                    value={suggestion}
                    onChange={handleSuggestionChange}
                    rows="5"
                    cols="50"
                  />
                </div>

            
                <Filter />
              </>
            } 
          />

         
          <Route path="/teacher/:teacherId" element={<TeacherBio />} />
        </Routes>
      </div>
      <StudentForm/>
<br></br>
      <Teacherfrom/>

      <br></br>

      <StudentFilter/>
    </Router>
    
  );
}

export default App;
